### ISSUE TITLE
Parsing JOA ne fonctionne plus

### ISSUE THREAD

**Issue by AoooR42** [pretrehr/Sports-betting#10]
Salut, je crois que le parsing de joa ne fonctionne plus (pas de message d'erreur, les équipes s'affichent mais pas les cotes)
![image](https://user-images.githubusercontent.com/77069582/104516005-e9089600-55f3-11eb-9a1c-6804f82fd02a.png)

**Comment by pretrehr** [comment]
Je n'ai pas ce problème de mon côté. Est-ce que cela arrive tout le temps ?

**Comment by AoooR42** [comment]
> Je n'ai pas ce problème de mon côté. Est-ce que cela arrive tout le temps ?

je viens de re tester et effectivement il n'y a plus ce problème, sans rien changer, peut etre que c'etait un soucis venant de joa qu'ils ont réglé. merci quand meme, bonne soirée

**Comment by pretrehr** [comment]
Super nouvelle ! Bonne soirée 😃
