### ISSUE TITLE
import sportsbetting as sb

### ISSUE THREAD

**Issue by Lafourb** [pretrehr/Sports-betting#17]
Bonjour,

Tout d'abord bravo pour le boulot, je rencontre une difficulté, sportsbetting n'est pas reconnu comme un module chez moi

![image](https://user-images.githubusercontent.com/78705778/107160442-89a16a00-6996-11eb-85ca-baad5c9ed851.png)

**Comment by pretrehr** [comment]
Bonjour
Merci pour votre message.
Pour l'importer en tant que module il faut déjà vous assurer que le dossier "sportsbetting" se trouve bien dans le répertoire courant. Pour cela, faites :
```
import os
os.getcwd()
```
Ensuite assurez-vous que le dossier affiché contienne bien un dossier "sportsbetting".
Si ce n'est pas le cas, placez-vous à la racine du projet "Sports-betting" que vous avez téléchargé (votre dossier courant doit alors être "Sports-betting" ou "Sports-betting-master"), et lancez python depuis ce dossier, cela devrait fonctionner.
Si cela ne marche pas, n'hésitez pas à me recontacter.

**Comment by Lafourb** [comment]
Merci ! 

Résolu !
