### ISSUE TITLE
Driver not started for unibet

### ISSUE THREAD

**Issue by NiicOw974** [pretrehr/Sports-betting#22]
Quand je lance l'interface graphique j'ai une erreur qui tourne en boucle.

Driver not started for unibet
Restarting driver

**Comment by pretrehr** [comment]
Bonjour
C'est corrigé !
Merci pour votre message.

**Comment by NiicOw974** [comment]
Bonjour, merci pour votre rapidité cependant j'ai la même erreur avec parionssport, betclic, unibet

J'ai augmenter le timeout à 30 et j'ai toujours l'erreur. les bookmakers concernés sont pas toujours les mêmes.

**Comment by NiicOw974** [comment]
idem pour betstars (timeout 45)

**Comment by NiicOw974** [comment]
idem joa (timeout 60)

**Comment by NiicOw974** [comment]
timeout 120 j'ai cet erreur.
![image](https://user-images.githubusercontent.com/43825795/108031498-6471c300-704a-11eb-88a7-b930651b057d.png)

**Comment by NiicOw974** [comment]
Personnellement j'aimerais utiliser uniquement winamax avec l'interface graphique.

**Comment by pretrehr** [comment]
Il est possible que le problème vienne du fait que vous utilisez une version trop ancienne de Chrome.
Mais si vous n'utilisez que Winamax alors vous pouvez simplement retirer la ligne 59 de interface_pysimplegui.py
`sb.selenium_init.start_drivers()`

**Comment by NiicOw974** [comment]
Je suis pourtant à jour sur la version de google chrome c'est bizarre.

d'accord je vais tester en enlevant cette ligne. Merci beaucoup je reviens vers vous si ça fonctionne.

**Comment by NiicOw974** [comment]
En supprimant la ligne ça fonctionne.

**Comment by pretrehr** [comment]
Je ferme l'issue. N'hésitez pas à la rouvrir si jamais vous voulez utilisez les autres bookmakers et que le problème est encore là.
