### ISSUE TITLE
No module named 'colorama'

### ISSUE THREAD

**Issue by Slibar** [pretrehr/Sports-betting#3]
Hi , i've tried to test your program but i have an issue.
I've install all the modules but still have this message : 

"Traceback (most recent call last):
  File "C:\prog_py\Sports-betting-master\interface_pysimplegui.py", line 20, in <module>
    from sportsbetting.auxiliary_functions import get_nb_issues
  File "C:\prog_py\Sports-betting-master\sportsbetting\auxiliary_functions.py", line 14, in <module>
    from sportsbetting.database_functions import (get_formatted_name, is_in_db_site, is_in_db,
  File "C:\prog_py\Sports-betting-master\sportsbetting\database_functions.py", line 4, in <module>
    import colorama
ModuleNotFoundError: No module named 'colorama'
>>>" 

Is there something i've done wrong ? ^^'

Thanks for the help anyway  !

Slibar

**Comment by pretrehr** [comment]
Hi Slibar,
Have you tried to install the package with the command `pip install colorama` ?
If it doesn't work, can you tell me which Python version are you using ?
Thank you
pretrehr

**Comment by Slibar** [comment]
It works !  I feel dumb because i didn't thing about installing it myself ..
I restart python after a looooong break .
Thanks for your help and for that huge program !

**Comment by pretrehr** [comment]
Good news :)
If the problem repeats with another package, you can just run `pip install -r requirements.txt` at the root of the project and you will have all the packages needed.
