### ISSUE TITLE
Récupération des cotes annexes

### ISSUE THREAD

**Issue by Vivalemuc** [pretrehr/Sports-betting#31]
Bonjour,

Franchement gros respect pour ton travail, c'est impressionnant !

Je suis développeur (plutot java), et j'aurais aimé t'aider, notamment pour récupérer d'autres types de côtes (genre les rebonds, les contres au basket etc), pour pouvoir detecter plus de surebets !

Penses-tu que cela soit possible ?

**Comment by pretrehr** [comment]
Salut ! 
Bien sûr, avec plaisir ! Je t'encourage à forker le repository puis à faire une pull request quand tu auras fini :)

**Comment by Vivalemuc** [comment]
Ma question était plutot penses-tu que cela possible d'intégrer d'autres type de cotes à ton programme ?
J'aurais besoin d'aide sur comment tu regroupes les paris notamment, comment tu juges un pari identique sur Betclic et FDJ par exemple ?

**Comment by pretrehr** [comment]
Ah oui désolé j'avais mal compris !
C'est toujours possible mais c'est assez contraignant parce qu'il faut repasser sur chaque match et associer les marchés secondaires entre eux à travers les différents bookmakers. Le problème c'est que ce mapping n'est pas si évident à faire entre les bookmakers. Déjà les noms des marchés varient entre les bookmakers, ensuite les valeurs ne sont pas systématiquement les mêmes entre les bookmakers (Betclic peut proposer K. Leonard fait +5.5 passes, alors que FDJ ne propose que +4.5 passes...) et enfin les noms des joueurs varient entre les bookmakers (comment comprendre que Le Bron James est le même joueur que L.James ou encore que J.Holiday se rapporte à Jrue Holiday et pas Justin Holiday, ....). 
Je t'avoue que ça fait un moment que j'y réfléchis mais ça demande pas mal d'investissement supplémentaire (notamment pour peupler une éventuelle base de données de mapping) par rapport à la récupération des cotes 1N2 disons.

**Comment by Vivalemuc** [comment]
Du coup on est d'accord, j'ai bien compris que c'était complexe, je me demandais simplement, ca aurait été une petite cerise sur le gateau :P 

Est-il possible d'ajouter une fonction dans les surebets ou l'on rentre la somme que l'on veut miser, et ils nous donne la répartition idéale ?

**Comment by pretrehr** [comment]
En fait, je pense que cette fonctionnalité est déjà implémentée dans l'onglet "Pari simple" lorsque vous cochez la case "Mise à répartir sur plusieurs issues d'un même match". Cela permet de répartir la somme que l'on doit miser chez un bookmaker de la manière la plus optimale. Selon les cotes disponibles, l'algorithme va vous proposer de tout miser sur une seule cote ou de répartir la mise sur 2 voire 3 issues d'un match chez le bookmaker voulu.

**Comment by Vivalemuc** [comment]
Non pas tout à fait ;)

<img width="273" alt="Capture_decran_2021-03-26_a_14 05 41" src="https://user-images.githubusercontent.com/12020461/112757736-56b94100-8feb-11eb-9140-cdff049a32db.png">

Par exemple pour ce match, l'algorithme devrait pouvoir me dire de miser X sur bwin, X sur pasinobet et X sur barrierebet pour répartir ma mise et gagner la même somme dans tous les cas ! Il ne s'agit pas de parier chez un seul book, mais sur les 3 pour gagner quoi qu'il arrive !

**Comment by pretrehr** [comment]
Salut !
Désolé pour la réponse tardive. J'ai rajouté dans l'onglet Cotes la possibilité de calculer la répartition idéale des mises pour le match sélectionné et pour une mise donnée. Normalement ça devrait correspondre à ce que tu voulais
